- name: Image Test
  hosts: all
  gather_facts: true
  roles:
    - role: geerlingguy.repo-epel
      become: true
      when: ansible_os_family == 'RedHat'
    - role: geerlingguy.repo-remi
      become: true
      when: ansible_os_family == 'RedHat'
    - role: geerlingguy.php
      become: true
    - role: geerlingguy.apache
      become: true
    - role: geerlingguy.mysql
      become: true
    - role: geerlingguy.composer
      become: true
  vars:
    # RHEL/CentOS Only
    php_enablerepo: remi
    # install PHP version
    php_version: 7.2
  tasks:
