# https://github.com/dev-sec/ansible-os-hardening
- src: dev-sec.os-hardening
# https://github.com/dev-sec/ansible-ssh-hardening
- src: dev-sec.ssh-hardening
- src: geerlingguy.mysql
- src: geerlingguy.apache
- src: geerlingguy.php
- src: geerlingguy.composer
